export const SIGN_UP = "Sign Up";
export const LOGIN = "Log In";
export const Get_Quote = "Get Quote"
import React from 'react';

  export const railingSevices = [
  'Custom Design and Fabrication', 
  'Installation of Steel Railings', 
  'Repair and Maintenance', 
  'Ornamental Steel Railings', 
  'Safety Compliance', 
  'Glass or Wood Infill Options',
  'Others'
];

  export const windowServices = [
  'Window Installation',
  'Custom Steel Windows',
  'Window Repair and Restoration',
  'Weatherproofing and Insulation',
  'Security Enhancements',
  'Decorative Steel Windows',
  'Commercial and Industrial Steel Windows',
  'Others'
];

  export const combinedServices = [
  'Integrated Design of Railing and Window',
  'Combined Maintenance Packages',
  'Eco-Friendly Solutions', 
  'Others'
];

 export const gates = [
  {
    "id": 1,
    "title": "Main Front Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate1.png",
    "description": "Elegant and modern main front gate design.",
    "brand": "S3",
    "sku": "GATE1",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 850",
    "discountedPrice": "Rs 750",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 2,
    "title": "Stainless Steel Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate2.png",
    "description": "Durable and sleek stainless steel gate.",
    "brand": "S4",
    "sku": "GATE2",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1000",
    "discountedPrice": "Rs 900",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 3,
    "title": "Iron Main Front Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate3.png",
    "description": "Classic and strong iron main front gate.",
    "brand": "S5",
    "sku": "GATE3",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1200",
    "discountedPrice": "Rs 1100",
    "discountPercentage": "8% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 4,
    "title": "4 Folding Gate Design",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate4.png",
    "description": "Space-saving 4 folding gate design.",
    "brand": "S6",
    "sku": "GATE4",
    "productType": "Folding Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 5,
    "title": "Simple Iron Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate5.png",
    "description": "Minimalistic and simple iron gate.",
    "brand": "S7",
    "sku": "GATE5",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 750",
    "discountedPrice": "Rs 650",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 6,
    "title": "Curtain Man Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate6.png",
    "description": "Intricately designed curtain man gate.",
    "brand": "S8",
    "sku": "GATE6",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1600",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 7,
    "title": "Modern Steel Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate7.png",
    "description": "Sleek modern design for residential properties.",
    "brand": "S9",
    "sku": "GATE7",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 8,
    "title": "Luxury Gate Design",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate8.png",
    "description": "High-end luxury gate with intricate designs.",
    "brand": "S10",
    "sku": "GATE8",
    "productType": "Luxury Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 9,
    "title": "Steel Gate with Glass Panels",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate9.png",
    "description": "Steel gate with glass panel inserts for added aesthetics.",
    "brand": "S11",
    "sku": "GATE9",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel with Glass Panels"
   },
   {
    "id": 10,
    "title": "Industrial Iron Gate",
    "image": "\/images\/gateImages\/doubledoorgate\/door_gate10.png",
    "description": "Robust iron gate with industrial design.",
    "brand": "S12",
    "sku": "GATE10",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 2000",
    "discountedPrice": "Rs 1800",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 11,
    "title": "Compact Folding Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate1.png",
    "description": "Compact and versatile folding gate for narrow spaces.",
    "brand": "S13",
    "sku": "GATE11",
    "productType": "Folding Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 1600",
    "discountedPrice": "Rs 1500",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 12,
    "title": "Traditional Wooden Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate2.png",
    "description": "Traditional wooden gate with a classic design.",
    "brand": "S14",
    "sku": "GATE12",
    "productType": "Wooden Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 2200",
    "discountedPrice": "Rs 2000",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood",
    "features": "Material - Wood"
   },
   {
    "id": 13,
    "title": "High Security Steel Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate3.png",
    "description": "High security steel gate with reinforced bars.",
    "brand": "S15",
    "sku": "GATE13",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 3000",
    "discountedPrice": "Rs 2700",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 14,
    "title": "Aluminum Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate4.png",
    "description": "Lightweight and durable aluminum gate.",
    "brand": "S16",
    "sku": "GATE14",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1700",
    "discountPercentage": "6% OFF",
    "materialGrade": "Aluminum",
    "features": "Material - Aluminum"
   },
   {
    "id": 15,
    "title": "Rustic Iron Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate5.png",
    "description": "Rustic design iron gate for vintage style homes.",
    "brand": "S17",
    "sku": "GATE15",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 16,
    "title": "Security Barrier Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate6.png",
    "description": "Security barrier gate for high-traffic areas.",
    "brand": "S18",
    "sku": "GATE16",
    "productType": "Barrier Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 4000",
    "discountedPrice": "Rs 3800",
    "discountPercentage": "5% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 17,
    "title": "Automatic Sliding Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate7.png",
    "description": "Automatic sliding gate with remote control.",
    "brand": "S19",
    "sku": "GATE17",
    "productType": "Sliding Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 18,
    "title": "Gate with LED Lights",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate8.png",
    "description": "Modern gate with integrated LED lighting.",
    "brand": "S20",
    "sku": "GATE18",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 19,
    "title": "Modern Steel Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate9.png",
    "description": "Sleek, modern steel gate design for modern homes.",
    "brand": "S21",
    "sku": "GATE19",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 20,
    "title": "Wooden with Metal Inserts Gate",
    "image": "\/images\/gateImages\/slidinggate\/slide_gate10.png",
    "description": "Wooden gate with metal inserts for a stylish touch.",
    "brand": "S22",
    "sku": "GATE20",
    "productType": "Wooden Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood with Metal",
    "features": "Material - Wood with Metal Inserts"
   }
];

export const railings = [
  {
    "id": 1,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail1.png",
    "description": "Solid steel railing with a contemporary, streamlined design.",
    "brand": "G1",
    "sku": "GLASSRAIL1",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 850",
    "discountedPrice": "Rs 750",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 2,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail2.png",
    "description": "Sleek and transparent glass railing for modern elegance.",
    "brand": "G2",
    "sku": "GLASSRAIL2",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1000",
    "discountedPrice": "Rs 900",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 3,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail3.png",
    "description": "Minimalist glass railing for a clean, open look.",
    "brand": "G3",
    "sku": "GLASSRAIL3",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1200",
    "discountedPrice": "Rs 1100",
    "discountPercentage": "8% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 4,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail4.png",
    "description": "High-quality glass railing that enhances natural light.",
    "brand": "G4",
    "sku": "GLASSRAIL4",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 5,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail5.png",
    "description": "Contemporary glass railing with stainless steel accents.",
    "brand": "G5",
    "sku": "GLASSRAIL5",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 750",
    "discountedPrice": "Rs 650",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 6,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail6.png",
    "description": "Stylish glass railing for a sophisticated, modern touch.",
    "brand": "G6",
    "sku": "GLASSRAIL6",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1600",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 7,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail7.png",
    "description": "Frameless glass railing for unobstructed views.",
    "brand": "G7",
    "sku": "GLASSRAIL7",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 8,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail8.png",
    "description": "Durable glass railing for both indoor and outdoor spaces.",
    "brand": "G8",
    "sku": "GLASSRAIL8",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 9,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail9.png",
    "description": "Modern glass railing with a sleek, minimalist design.",
    "brand": "G9",
    "sku": "GLASSRAIL9",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel with Glass Panels"
   },
   {
    "id": 10,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail10.png",
    "description": "Elegant glass railing for luxurious balconies and staircases.",
    "brand": "G10",
    "sku": "GLASSRAIL10",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 2000",
    "discountedPrice": "Rs 1800",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 11,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail11.png",
    "description": "Clear glass railing with a contemporary, clean aesthetic.",
    "brand": "G11",
    "sku": "GLASSRAIL11",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1600",
    "discountedPrice": "Rs 1500",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 12,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail12.png",
    "description": "Safety-conscious glass railing with sturdy metal supports.",
    "brand": "G12",
    "sku": "GLASSRAIL12",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 2200",
    "discountedPrice": "Rs 2000",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood",
    "features": "Material - Wood"
   },
   {
    "id": 13,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail13.png",
    "description": "Stylish glass railing with a seamless, polished finish.",
    "brand": "G13",
    "sku": "GLASSRAIL13",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 3000",
    "discountedPrice": "Rs 2700",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 14,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail14.png",
    "description": "Premium glass railing perfect for high-end properties.",
    "brand": "G14",
    "sku": "GLASSRAIL14",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1700",
    "discountPercentage": "6% OFF",
    "materialGrade": "Steel",
    "features": "Material - Aluminum"
   },
   {
    "id": 15,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail15.png",
    "description": "Contemporary glass railing that adds a touch of elegance.",
    "brand": "G15",
    "sku": "GLASSRAIL15",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 16,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail16.png",
    "description": "Clear glass railing for an open and airy feel.",
    "brand": "G16",
    "sku": "GLASSRAIL16",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 4000",
    "discountedPrice": "Rs 3800",
    "discountPercentage": "5% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 17,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail17.png",
    "description": "Frameless glass railing that complements modern architecture.",
    "brand": "G17",
    "sku": "GLASSRAIL17",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 18,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail18.png",
    "description": "Glass railing with subtle metal trim for a refined look.",
    "brand": "G18",
    "sku": "GLASSRAIL18",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 19,
    "title": "Glass Railing",
    "image": "\/images\/railingImages\/glassRailing\/glass_rail19.png",
    "description": "Safe and sturdy glass railing ideal for modern homes.",
    "brand": "G19",
    "sku": "GLASSRAIL19",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 20,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rai1.png",
    "description": "Elegant glass railing with a minimalist stainless steel frame.",
    "brand": "G20",
    "sku": "STEELRAIL1",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood with Metal",
    "features": "Material - Wood with Metal Inserts"
   },
   {
    "id": 21,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/stillRailing\/steel_rai2.png",
    "description": "Elegant steel railing for both indoor and outdoor use.",
    "brand": "G21",
    "sku": "STEELRAIL2",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1600",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 22,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rai3.png",
    "description": "High-quality steel railing with smooth, polished finish.",
    "brand": "G22",
    "sku": "STEELRAIL3",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 23,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rai4.png",
    "description": "Durable steel railing with a minimalist design.",
    "brand": "G23",
    "sku": "STEELRAIL4",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 24,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rai5.png",
    "description": "Elegant steel railing for both indoor and outdoor use.",
    "brand": "G24",
    "sku": "STEELRAIL5",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 25,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rai6.png",
    "description": "High-quality steel railing with smooth, polished finish.",
    "brand": "G25",
    "sku": "STEELRAIL6",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2000",
    "discountedPrice": "Rs 1800",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 26,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rai7.png",
    "description": "Industrial-style steel railing for urban properties.",
    "brand": "G26",
    "sku": "STEELRAIL7",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1600",
    "discountedPrice": "Rs 1500",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 27,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail1.png",
    "description": "Modern steel railing with geometric pattern details.",
    "brand": "G27",
    "sku": "STEELRAIL8",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2200",
    "discountedPrice": "Rs 2000",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 28,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail2.png",
    "description": "Stylish steel railing to complement any modern home.",
    "brand": "G28",
    "sku": "STEELRAIL9",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 3000",
    "discountedPrice": "Rs 2700",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 29,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail3.png",
    "description": "Strong and durable steel railing for enhanced security.",
    "brand": "G29",
    "sku": "STEELRAIL10",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1700",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel with Glass Panels"
   },
   {
    "id": 30,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail4.png",
    "description": "Simple yet refined steel railing for a timeless look.",
    "brand": "G30",
    "sku": "STEELRAIL11",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 31,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail5.png",
    "description": "Robust steel railing ideal for high-traffic areas.",
    "brand": "G31",
    "sku": "STEELRAIL12",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 4000",
    "discountedPrice": "Rs 3800",
    "discountPercentage": "5% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 32,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail6.png",
    "description": "Clean-lined steel railing with an ultra-modern touch.",
    "brand": "G32",
    "sku": "STEELRAIL13",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Wood",
    "features": "Material - Wood"
   },
   {
    "id": 33,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail7.png",
    "description": "Customizable steel railing to suit every home style.",
    "brand": "G33",
    "sku": "STEELRAIL14",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 34,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail8.png",
    "description": "Stylish stainless steel railing with sleek bars.",
    "brand": "G34",
    "sku": "STEELRAIL15",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Steel",
    "features": "Material - Aluminum"
   },
   {
    "id": 35,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail9.png",
    "description": "Powder-coated steel railing for long-lasting durability.",
    "brand": "G35",
    "sku": "STEELRAIL16",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 36,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail10.png",
    "description": "Strong steel railing with a minimalist aesthetic.",
    "brand": "G36",
    "sku": "STEELRAIL17",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 37,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail11.png",
    "description": "Contemporary steel railing with refined, smooth bars.",
    "brand": "G37",
    "sku": "STEELRAIL18",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 4000",
    "discountedPrice": "Rs 3800",
    "discountPercentage": "5% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 38,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail12.png",
    "description": "Elegant steel railing with decorative detail for added flair.",
    "brand": "G38",
    "sku": "STEELRAIL19",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 39,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail13.png",
    "description": "Versatile steel railing that suits both modern and traditional homes.",
    "brand": "G39",
    "sku": "STEELRAIL20",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 40,
    "title": "Steel Railing",
    "image": "\/images\/railingImages\/steelRailing\/steel_rail14.png",
    "description": "Stainless steel railing with a premium finish for luxury homes.",
    "brand": "G40",
    "sku": "STEELRAIL21",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Wood with Metal",
    "features": "Material - Wood with Metal Inserts"
   }
];