export const SIGN_UP = "Sign Up";
export const LOGIN = "Log In";
export const Get_Quote = "Get Quote"
import React from 'react';
import { Shield, Users, Award, Clock, AppWindow as Window, PenTool as Tool, Settings } from 'lucide-react';

export const services = [
  {
    icon: <Shield className="w-12 h-12 text-blue-600" />,
    title: 'Custom Railing Design',
    description: 'Bespoke railing solutions tailored to your specific needs and style preferences.'
  },
  {
    icon: <Window className="w-12 h-12 text-blue-600" />,
    title: 'Window Installation',
    description: 'Professional window installation services with energy-efficient options.'
  },
  {
    icon: <Tool className="w-12 h-12 text-blue-600" />,
    title: 'Repair Services',
    description: 'Expert repair services for both railings and windows to ensure lasting durability.'
  },
  {
    icon: <Settings className="w-12 h-12 text-blue-600" />,
    title: 'Maintenance',
    description: 'Regular maintenance services to keep your installations in perfect condition.'
  }
];

export const projects = [
  {
    id: 1,
    title: 'Modern Staircase Railing',
    category: 'railings',
    image: '/Images/railingImages/glassRailing/glass_rail1.png'
  },
  {
    id: 2,
    title: 'Energy-Efficient Windows',
    category: 'windows',
    image: '/Images/windowImages/aluminiumWin/alumwin10.png'
  },
  {
    id: 3,
    title: 'Glass Balcony Railing',
    category: 'railings',
    image: '/Images/railingImages/glassRailing/glass_rail7.png'
  },
  {
    id: 4,
    title: 'Commercial Windows',
    category: 'windows',
    image: '/Images/windowImages/aluminiumWin/alumwin7.png'
  },
  {
    id: 5,
    title: 'Commercial Gates',
    category: 'gates',
    image: '/Images/gateImages/slidinggate/slide_gate5.png'
  },
  {
    id: 6,
    title: 'Custom Steel Railing',
    category: 'railings',
    image: '/Images/railingImages/steelRailing/steel_rai4.png'
  },
  {
    id: 7,
    title: 'Custom Sliding Gates',
    category: 'gates',
    image: '/Images/gateImages/slidinggate/slide_gate1.png'
  },
  {
    id: 8,
    title: 'Residential Windows',
    category: 'windows',
    image: '/Images/windowImages/steelGrillWin/grill_win2.png'
  },
  {
    id: 9,
    title: 'Residential Gates',
    category: 'gates',
    image: '/Images/gateImages/doubledoorgate/door_gate9.png'
  }
];

export const testimonials = [
  {
    name: 'Rakesh Sharma',
    image: '/Images/boy1.png',
    rating: '⭐⭐⭐⭐⭐',
    feedback: 'Modern steel railing team transformed our home with stunning railings that not only look beautiful but also enhance our safety. The team was professional and attentive to our needs.',
  },
  {
    name: 'Arjun Sing',
    image: '/Images/boy2.png',
    rating: '⭐⭐⭐⭐⭐',
    feedback: 'The window installation service was seamless from start to finish. The new windows have made a huge difference in energy efficiency and appearance. Highly recommend!',
  },
  {
    name: 'Krishna Reddy',
    image: '/Images/boy3.png',
    rating: '⭐⭐⭐⭐⭐',
    feedback: 'Our experience with modern steel railing team was fantastic. They delivered on time and exceeded our expectations with their attention to detail. Our new railings are a perfect blend of functionality and style.',
  },
  {
    name: 'Aahana Kapoor',
    image: '/Images/girl1.png',
    rating: '⭐⭐⭐⭐⭐',
    feedback: 'Working with modern steel railing team was a fantastic experience. They delivered ahead of schedule and their attention to detail was remarkable. The railings are not only stylish but also incredibly sturdy, adding the perfect finishing touch to our home',
  },
  {
    name: 'Ishani Yadav',
    image: '/Images/girl2.png',
    rating: '⭐⭐⭐⭐⭐',
    feedback: 'modern steel railing team truly impressed us with their service. From the initial consultation to the final installation, everything was seamless. The new windows and railings have transformed our home, combining both beauty and durability.',
  }
];

export const galleryItems = [
  {
    title: 'Transform Your Space',
    description: 'Elevate your property with our tailored railing solutions, combining aesthetic appeal with superior safety.',
    image: '/Images/otherImages/steel_rail1.png',
  },
  {
    title: 'Unmatched Quality',
    description: 'Our precision window installations are designed to improve energy efficiency while enhancing your property’s visual appeal.',
    image: '/Images/otherImages/alumwin1.png',
  },
  {
    title: 'Safety and Durability',
    description: 'Our railings are built with the highest standards of safety and durability, ensuring peace of mind for every homeowner.',
    image: '/Images/otherImages/steel_rail4.png',
  },
  {
    title: 'Custom Designs',
    description: 'Bespoke railing designs tailored to fit your unique style and functional needs can transform any space into a statement.',
    image: '/Images/otherImages/steel_rail3.png',
  },
  {
    title: 'Elevate Aesthetics',
    description: 'Windows that match your décor and enhance your home’s charm while maintaining energy efficiency are within your reach.',
    image: '/Images/otherImages/alumwin2.png',
  },
  {
    title: 'Precision Installation',
    description: 'Our expert team guarantees seamless installations, adhering to the tightest schedules while maintaining the highest standards.',
    image: '/Images/otherImages/slide_gate1.png',
  },
  {
    title: 'Inspiring Craftsmanship',
    description: 'Highlighting fine details, each railing and window reflects a commitment to artistry and quality that you can rely on.',
    image: '/Images/otherImages/glass_rail1.png',
  },
  {
    title: 'Timeless Appeal',
    description: 'Discover how our premium materials and sleek designs combine to create enduring beauty in your living and workspaces.',
    image: '/Images/otherImages/billboard.png',
  },
];

export const features = [
  {
    icon: <Shield className="w-12 h-12 text-blue-600" />,
    title: '20+ Years Experience',
    description: 'Decades of expertise in custom railing and window solutions.'
  },
  {
    icon: <Users className="w-12 h-12 text-blue-600" />,
    title: 'Expert Team',
    description: 'Highly skilled craftsmen and certified installers.'
  },
  {
    icon: <Award className="w-12 h-12 text-blue-600" />,
    title: 'Quality Guaranteed',
    description: 'Premium materials and industry-leading warranties.'
  },
  {
    icon: <Clock className="w-12 h-12 text-blue-600" />,
    title: 'Timely Delivery',
    description: 'On-time project completion and professional installation.'
  }
];

  export const railingServices = [
  'Custom Design and Fabrication', 
  'Installation of Steel Railings', 
  'Repair and Maintenance', 
  'Ornamental Steel Railings', 
  'Safety Compliance', 
  'Glass or Wood Infill Options',
  'Others'
];

  export const windowServices = [
  'Window Installation',
  'Custom Steel Windows',
  'Window Repair and Restoration',
  'Weatherproofing and Insulation',
  'Security Enhancements',
  'Decorative Steel Windows',
  'Commercial and Industrial Steel Windows',
  'Others'
];

  export const gateServices = [
  'Custom Design & Fabrication',
  'Gate Installation',
  'Repairs & Maintenance of Gate', 
  'Security Enhancements',
  'Residential Gates',
  'Commercial and Industrial Steel Gates',
  'Others'
];

export const gates = [
  {
    "id": 1,
    "title": "Main Front Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate1.png",
    "description": "Elegant and modern main front gate design.",
    "brand": "S3",
    "sku": "GATE1",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 850",
    "discountedPrice": "Rs 750",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 2,
    "title": "Stainless Steel Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate2.png",
    "description": "Durable and sleek stainless steel gate.",
    "brand": "S4",
    "sku": "GATE2",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1000",
    "discountedPrice": "Rs 900",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 3,
    "title": "Iron Main Front Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate3.png",
    "description": "Classic and strong iron main front gate.",
    "brand": "S5",
    "sku": "GATE3",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1200",
    "discountedPrice": "Rs 1100",
    "discountPercentage": "8% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 4,
    "title": "4 Folding Gate Design",
    "image": "/Images/gateImages/doubledoorgate/door_gate4.png",
    "description": "Space-saving 4 folding gate design.",
    "brand": "S6",
    "sku": "GATE4",
    "productType": "Folding Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 5,
    "title": "Simple Iron Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate5.png",
    "description": "Minimalistic and simple iron gate.",
    "brand": "S7",
    "sku": "GATE5",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 750",
    "discountedPrice": "Rs 650",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 6,
    "title": "Curtain Man Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate6.png",
    "description": "Intricately designed curtain man gate.",
    "brand": "S8",
    "sku": "GATE6",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1600",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 7,
    "title": "Modern Steel Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate7.png",
    "description": "Sleek modern design for residential properties.",
    "brand": "S9",
    "sku": "GATE7",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 8,
    "title": "Luxury Gate Design",
    "image": "/Images/gateImages/doubledoorgate/door_gate8.png",
    "description": "High-end luxury gate with intricate designs.",
    "brand": "S10",
    "sku": "GATE8",
    "productType": "Luxury Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 9,
    "title": "Steel Gate with Glass Panels",
    "image": "/Images/gateImages/doubledoorgate/door_gate9.png",
    "description": "Steel gate with glass panel inserts for added aesthetics.",
    "brand": "S11",
    "sku": "GATE9",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel with Glass Panels"
   },
   {
    "id": 10,
    "title": "Industrial Iron Gate",
    "image": "/Images/gateImages/doubledoorgate/door_gate10.png",
    "description": "Robust iron gate with industrial design.",
    "brand": "S12",
    "sku": "GATE10",
    "productType": "Gate",
    "category": "DoubleDoorGate",
    "originalPrice": "Rs 2000",
    "discountedPrice": "Rs 1800",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 11,
    "title": "Compact Folding Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate1.png",
    "description": "Compact and versatile folding gate for narrow spaces.",
    "brand": "S13",
    "sku": "GATE11",
    "productType": "Folding Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 1600",
    "discountedPrice": "Rs 1500",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 12,
    "title": "Traditional Wooden Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate2.png",
    "description": "Traditional wooden gate with a classic design.",
    "brand": "S14",
    "sku": "GATE12",
    "productType": "Wooden Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 2200",
    "discountedPrice": "Rs 2000",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood",
    "features": "Material - Wood"
   },
   {
    "id": 13,
    "title": "High Security Steel Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate3.png",
    "description": "High security steel gate with reinforced bars.",
    "brand": "S15",
    "sku": "GATE13",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 3000",
    "discountedPrice": "Rs 2700",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 14,
    "title": "Aluminum Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate4.png",
    "description": "Lightweight and durable aluminum gate.",
    "brand": "S16",
    "sku": "GATE14",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1700",
    "discountPercentage": "6% OFF",
    "materialGrade": "Aluminum",
    "features": "Material - Aluminum"
   },
   {
    "id": 15,
    "title": "Rustic Iron Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate5.png",
    "description": "Rustic design iron gate for vintage style homes.",
    "brand": "S17",
    "sku": "GATE15",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 16,
    "title": "Security Barrier Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate6.png",
    "description": "Security barrier gate for high-traffic areas.",
    "brand": "S18",
    "sku": "GATE16",
    "productType": "Barrier Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 4000",
    "discountedPrice": "Rs 3800",
    "discountPercentage": "5% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 17,
    "title": "Automatic Sliding Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate7.png",
    "description": "Automatic sliding gate with remote control.",
    "brand": "S19",
    "sku": "GATE17",
    "productType": "Sliding Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 18,
    "title": "Gate with LED Lights",
    "image": "/Images/gateImages/slidinggate/slide_gate8.png",
    "description": "Modern gate with integrated LED lighting.",
    "brand": "S20",
    "sku": "GATE18",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 19,
    "title": "Modern Steel Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate9.png",
    "description": "Sleek, modern steel gate design for modern homes.",
    "brand": "S21",
    "sku": "GATE19",
    "productType": "Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 20,
    "title": "Wooden with Metal Inserts Gate",
    "image": "/Images/gateImages/slidinggate/slide_gate10.png",
    "description": "Wooden gate with metal inserts for a stylish touch.",
    "brand": "S22",
    "sku": "GATE20",
    "productType": "Wooden Gate",
    "category": "SlidingGate",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood with Metal",
    "features": "Material - Wood with Metal Inserts"
   }
];

export const railings = [
  {
    "id": 1,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail1.png",
    "description": "Solid steel railing with a contemporary, streamlined design.",
    "brand": "G1",
    "sku": "GLASSRAIL1",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 850",
    "discountedPrice": "Rs 750",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 2,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail2.png",
    "description": "Sleek and transparent glass railing for modern elegance.",
    "brand": "G2",
    "sku": "GLASSRAIL2",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1000",
    "discountedPrice": "Rs 900",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 3,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail3.png",
    "description": "Minimalist glass railing for a clean, open look.",
    "brand": "G3",
    "sku": "GLASSRAIL3",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1200",
    "discountedPrice": "Rs 1100",
    "discountPercentage": "8% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 4,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail4.png",
    "description": "High-quality glass railing that enhances natural light.",
    "brand": "G4",
    "sku": "GLASSRAIL4",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 5,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail5.png",
    "description": "Contemporary glass railing with stainless steel accents.",
    "brand": "G5",
    "sku": "GLASSRAIL5",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 750",
    "discountedPrice": "Rs 650",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 6,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail6.png",
    "description": "Stylish glass railing for a sophisticated, modern touch.",
    "brand": "G6",
    "sku": "GLASSRAIL6",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1600",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 7,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail7.png",
    "description": "Frameless glass railing for unobstructed views.",
    "brand": "G7",
    "sku": "GLASSRAIL7",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 8,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail8.png",
    "description": "Durable glass railing for both indoor and outdoor spaces.",
    "brand": "G8",
    "sku": "GLASSRAIL8",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 9,
    "title": "Glass Railing",
    "image": "/Images/railingImages/glassRailing/glass_rail9.png",
    "description": "Modern glass railing with a sleek, minimalist design.",
    "brand": "G9",
    "sku": "GLASSRAIL9",
    "productType": "Glass Railing",
    "category": "glassrailing",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel with Glass Panels"
   },
   {
    "id": 22,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rai3.png",
    "description": "High-quality steel railing with smooth, polished finish.",
    "brand": "G22",
    "sku": "STEELRAIL3",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 23,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rai4.png",
    "description": "Durable steel railing with a minimalist design.",
    "brand": "G23",
    "sku": "STEELRAIL4",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 24,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rai5.png",
    "description": "Elegant steel railing for both indoor and outdoor use.",
    "brand": "G24",
    "sku": "STEELRAIL5",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel 304 grade"
   },
   {
    "id": 25,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rai6.png",
    "description": "High-quality steel railing with smooth, polished finish.",
    "brand": "G25",
    "sku": "STEELRAIL6",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2000",
    "discountedPrice": "Rs 1800",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   },
   {
    "id": 26,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rai7.png",
    "description": "Industrial-style steel railing for urban properties.",
    "brand": "G26",
    "sku": "STEELRAIL7",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1600",
    "discountedPrice": "Rs 1500",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 27,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rail1.png",
    "description": "Modern steel railing with geometric pattern details.",
    "brand": "G27",
    "sku": "STEELRAIL8",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 2200",
    "discountedPrice": "Rs 2000",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 28,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rail2.png",
    "description": "Stylish steel railing to complement any modern home.",
    "brand": "G28",
    "sku": "STEELRAIL9",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 3000",
    "discountedPrice": "Rs 2700",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel"
   },
   {
    "id": 29,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rail3.png",
    "description": "Strong and durable steel railing for enhanced security.",
    "brand": "G29",
    "sku": "STEELRAIL10",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1700",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Material - Stainless Steel with Glass Panels"
   },
   {
    "id": 30,
    "title": "Steel Railing",
    "image": "/Images/railingImages/steelRailing/steel_rail4.png",
    "description": "Simple yet refined steel railing for a timeless look.",
    "brand": "G30",
    "sku": "STEELRAIL11",
    "productType": "Steel Railing",
    "category": "steelrailing",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 202",
    "features": "Material - Iron"
   }
];

export const windows = [
  {
    "id": 1,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin1.png",
    "description": "Premium aluminium windows with a sleek, modern finish.",
    "brand": "W1",
    "sku": "ALUMWIN1",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 850",
    "discountedPrice": "Rs 750",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Aluminium windows are highly resistant to corrosion, weathering, and rust, ensuring long-lasting performance in all climates"
   },
   {
    "id": 2,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin2.png",
    "description": "Contemporary aluminium frames that offer a refined, minimalist look.",
    "brand": "W2",
    "sku": "ALUMWIN2",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 1000",
    "discountedPrice": "Rs 900",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "With a slim profile and modern finish, aluminium frames provide a clean, contemporary look that suits a wide range of architectural styles."
   },
   {
    "id": 3,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin3.png",
    "description": "Elegant aluminium windows that blend durability with style.",
    "brand": "W3",
    "sku": "ALUMWIN3",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 1200",
    "discountedPrice": "Rs 1100",
    "discountPercentage": "8% OFF",
    "materialGrade": "Grade 202",
    "features": "Aluminium windows often come with thermal breaks and insulated glazing, improving energy efficiency by reducing heat loss and keeping indoor temperatures comfortable."
   },
   {
    "id": 4,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin4.png",
    "description": "High-performance aluminium windows designed to maximize natural light.",
    "brand": "W4",
    "sku": "ALUMWIN4",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 304",
    "features": "Aluminium frames are easy to clean and require little maintenance over time. They don’t need to be painted or treated frequently"
   },
   {
    "id": 5,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin5.png",
    "description": "Modern aluminium windows with clean lines and a polished, sophisticated appearance.",
    "brand": "W5",
    "sku": "ALUMWIN5",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 750",
    "discountedPrice": "Rs 650",
    "discountPercentage": "13% OFF",
    "materialGrade": "Grade 202",
    "features": "Despite their lightweight nature, aluminium frames are incredibly strong and can support larger panes of glass, creating a more open and airy look."
   },
   {
    "id": 6,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin6.png",
    "description": "Stylish glass railing for a sophisticated, modern touch.",
    "brand": "W6",
    "sku": "ALUMWIN6",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1600",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Aluminium is a recyclable material, making it an environmentally sustainable choice for windows."
   },
   {
    "id": 7,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin7.png",
    "description": "Stylish aluminium windows with a smooth, refined design.",
    "brand": "W7",
    "sku": "ALUMWIN7",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 1400",
    "discountedPrice": "Rs 1300",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 304",
    "features": "Aluminium windows are sturdy and can be fitted with multi-locking systems, enhancing the safety and security of your home or building."
   },
   {
    "id": 8,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin8.png",
    "description": "Durable aluminium frames that provide a modern, sleek aesthetic.",
    "brand": "W8",
    "sku": "ALUMWIN8",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Available in a variety of finishes and colors, aluminium windows can be customized to match any interior or exterior style."
   },
   {
    "id": 9,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin9.png",
    "description": "Contemporary aluminium windows that enhance your space with crisp lines.",
    "brand": "W9",
    "sku": "ALUMWIN9",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 2500",
    "discountedPrice": "Rs 2200",
    "discountPercentage": "12% OFF",
    "materialGrade": "Grade 304",
    "features": "Aluminium is highly resistant to extreme temperatures, making it suitable for both hot and cold climates"
   },
   {
    "id": 10,
    "title": "Aluminium Window",
    "image": "/Images/windowImages/aluminiumWin/alumwin10.png",
    "description": "Elegant aluminium windows designed for strength and visual appeal.",
    "brand": "W10",
    "sku": "ALUMWIN10",
    "productType": "Aluminium Window",
    "category": "aluminiumwindow",
    "originalPrice": "Rs 2000",
    "discountedPrice": "Rs 1800",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 202",
    "features": "The slim frames allow for larger glass areas, maximizing the amount of natural light entering the space, which helps brighten interiors."
   },
   {
    "id": 11,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win1.png",
    "description": "Stylish grill windows that add a sophisticated edge to any space.",
    "brand": "W11",
    "sku": "GRILLWIN1",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 1600",
    "discountedPrice": "Rs 1500",
    "discountPercentage": "6% OFF",
    "materialGrade": "Grade 304",
    "features": "Grill windows provide an added layer of protection against break-ins, keeping your home or office safe without sacrificing ventilation."
   },
   {
    "id": 12,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win2.png",
    "description": "Sturdy grill windows that combine security with a timeless design.",
    "brand": "W12",
    "sku": "GRILLWIN2",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 2200",
    "discountedPrice": "Rs 2000",
    "discountPercentage": "9% OFF",
    "materialGrade": "Wood",
    "features": "Made from strong materials like steel or wrought iron, grill windows are built to withstand impact and wear, offering long-term reliability."
   },
   {
    "id": 13,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win3.png",
    "description": "Elegant grill windows offering enhanced protection without compromising style.",
    "brand": "W13",
    "sku": "GRILLWIN3",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 3000",
    "discountedPrice": "Rs 2700",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Despite their protective design, grill windows allow for proper airflow, ensuring that your space remains well-ventilated and fresh."
   },
   {
    "id": 14,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win4.png",
    "description": "Modern grill windows with a clean, structured look.",
    "brand": "W14",
    "sku": "GRILLWIN4",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 1800",
    "discountedPrice": "Rs 1700",
    "discountPercentage": "6% OFF",
    "materialGrade": "Steel",
    "features": "Grill windows can be tailored to fit various design preferences, offering a wide range of patterns, finishes, and sizes to match your aesthetic."
   },
   {
    "id": 15,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win5.png",
    "description": "High-quality grill windows that blend functionality with aesthetic appeal.",
    "brand": "W15",
    "sku": "GRILLWIN5",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 1500",
    "discountedPrice": "Rs 1400",
    "discountPercentage": "7% OFF",
    "materialGrade": "Grade 202",
    "features": "Grill windows require minimal upkeep, needing only occasional cleaning to maintain their appearance and functionality."
   },
   {
    "id": 16,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win6.png",
    "description": "Durable grill windows with a sleek, contemporary finish.",
    "brand": "W16",
    "sku": "GRILLWIN6",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 4000",
    "discountedPrice": "Rs 3800",
    "discountPercentage": "5% OFF",
    "materialGrade": "Grade 304",
    "features": "Available in both traditional and modern styles, grill windows can enhance the visual appeal of your home, adding decorative value while offering security."
   },
   {
    "id": 17,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win7.png",
    "description": "Classic grill windows that provide both security and visual charm.",
    "brand": "W17",
    "sku": "GRILLWIN7",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 5000",
    "discountedPrice": "Rs 4500",
    "discountPercentage": "10% OFF",
    "materialGrade": "Grade 304",
    "features": "Their design often allows for larger openings without compromising safety, making them ideal for spaces that need extra light and air flow."
   },
   {
    "id": 18,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win8.png",
    "description": "Robust grill windows with a refined, modern design.",
    "brand": "W18",
    "sku": "GRILLWIN8",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 3500",
    "discountedPrice": "Rs 3200",
    "discountPercentage": "9% OFF",
    "materialGrade": "Grade 304",
    "features": "Many grill windows are coated with rust-resistant finishes, ensuring they remain in great condition even in damp or coastal environments."
   },
   {
    "id": 19,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win9.png",
    "description": "Decorative grill windows that offer reliable protection with style.",
    "brand": "W19",
    "sku": "GRILLWIN9",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Grill windows can provide a secondary layer of protection in case of fire, helping to slow the spread of flames while still allowing for escape routes if necessary."
   },
   {
    "id": 20,
    "title": "Grill Window",
    "image": "/Images/windowImages/steelGrillWin/grill_win10.png",
    "description": "Contemporary grill windows with a sleek, geometric pattern.",
    "brand": "W20",
    "sku": "GRILLWIN10",
    "productType": "Grill Window",
    "category": "grillwindow",
    "originalPrice": "Rs 2800",
    "discountedPrice": "Rs 2500",
    "discountPercentage": "11% OFF",
    "materialGrade": "Grade 304",
    "features": "Grill windows offer a cost-effective solution for improving security without the need for expensive alternatives."
   }
]